### PR TITLE
Programming the FPGA via AWS

### PR DESCRIPTION
**Pull request by tvannoy**
# Summary
This PR facilitates downloading and loading designs/demos from AWS. To keep things modular, and hopefully useful for future use cases that don't necessarily involve AWS, this PR contains three separate scripts that
1. Download the bitstream, device tree overlays, and drivers from AWS
2. Load the overlays and program the FPGA
3. Load the kernel modules

**Example usage:**
```bash
# download files from AWS
./awsdownload.py -b nih-demos -d audiomini/sound-effects
# load device tree overlay / program the FPGA
./overlaymgr.sh load sound_effects
# load the kernel modules
./driver.mgr.sh load sound_effects
```
Ultimately, these scripts will be called by a node js server or by another script. 

# Naming conventions
I've created the following conventions, which are certainly up for debate:
- rbf and dtbo files are named according to the Quartus project they belong to, e.g. `sound_effects.rbf`, `passthrough.dtbo`, etc. 
- S3 folders are named according to the <product>/<project>, except they use hyphens instead of underscores because those keys end up in URLs. For example, the sound effects projects lives at `audiomini/sound-effects`, and the Audio Blade passthrough would live at `audioblade/passthrough`
    - We could add hyphens in the product names for readability

Currently, these scripts somewhat rely on these naming conventions

# AWS downloader
This script, `awsdownload.py`, takes two primary arguments: 
- S3 bucket name where the demos are located
- directory where the demos are located inside the aforementioned S3 bucket 

It downloads the rbf, dtbo, and ko files from the user-supplied directory. It ignores all other files. 

It does not require AWS credentials to be set up; our bucket is fully public now. 

## Conventions
By default, the script puts the rbf and dtbo files in `/lib/firmware/`, as that directory is commonly what's used for storing firmware and device tree overlays. It puts kernel modules into `/lib/modules/<project>`. `/lib/modules/` is the standard location for loadable kernel modules, and I decided to group modules by project. Other ideas are welcome. 

**Danger!**
Unfortunately, there is coupling between where this script puts the files and where the other scripts expect the files to be. Changing the file locations in one script will affect the others. It would be nice to decouple this, or at least add some more flexibility to the overlay and driver manager scripts. 

## Performance
Download tend to take about 3-4 seconds on the DE10-Nano when using `awsdownload.py`. An alternative script, started by @fe-tdavis, has users supply all of the file names to download; this generally takes the same amount of download time as `awsdownload.py`, but has had less variation during testing; I suspect this is just a matter of unrelated OS/networking problems, but further performance optimization can be made if we find download times are annoyingly long. 

```
===> multitime results
1: -q ./awsdownload.py -b nih-demos -d audiomini/sound-effects
            Mean        Std.Dev.    Min         Median      Max
real        4.262       2.267       3.705       3.945       20.100
user        2.628       0.054       2.498       2.635       2.733
sys         0.459       0.090       0.241       0.475       0.611
===> multitime results
1: -q ./download_files.py -b nih-demos -d audiomini/sound-effects/ -fl sound_effects.rbf sound_effects.dtbo flanger.ko echo.ko bitcrusher.ko
            Mean        Std.Dev.    Min         Median      Max
real        3.766       0.143       3.583       3.759       4.361
user        2.617       0.052       2.491       2.620       2.718
sys         0.373       0.110       0.195       0.341       0.609
```

## Usage
```
usage: awsdownload.py -d DIRECTORY -b BUCKET [-h] [-v]
                      [--firmware-path FIRMWARE_PATH]
                      [--driver-path DRIVER_PATH]

required arguments:
  -d DIRECTORY, --directory DIRECTORY
                        S3 directory to download files from
  -b BUCKET, --bucket BUCKET
                        S3 bucket name

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         print verbose output
  --firmware-path FIRMWARE_PATH
                        path where bitstreams and overlays get placed
                        (default: /lib/firmware/)
  --driver-path DRIVER_PATH
                        path prefix where kernel modules folder gets created
                        (default: /lib/modules/)
```

# Overlay manager
`overlaymgr.sh` loads and removes device tree overlays. It uses [configfs overlays](https://github.com/altera-opensource/linux-socfpga/blob/socfpga-5.5/Documentation/devicetree/configfs-overlays.txt), which must be enabled in the kernel. 

The overlay contains a fragment that tells the [FPGA Manager](https://www.kernel.org/doc/html/latest/driver-api/fpga/fpga-mgr.html) to program the FPGA with the desired rbf. It also optionally contains fragments for devices in the FPGA fabric. 

This script assumes that the rbf and dtbo are on the system path. By placing those files in `/lib/firmware`, this requirement is met. 

## Usage 
```
usage: overlaymgr [-h] [-v] <command> overlay

Load and remove device tree overlays.

commands:
  load            load a device tree overlay
  remove          remove a device tree overlay

positional arguments:
  overlay         the name of the overlay file to load/remove

optional arguments:
  -h, --help      display this help text
  -v, --verbose   print more details about what's going on
```
## Example Overlay
```dts
/dts-v1/ /plugin/;
&fpga_region {
    firmware-name = "sound_effects.rbf";
    status = "sound effects rbf loaded";
};

&hps_bridges {
    #address-cells = <2>;
    #size-cells = <1>;
    ranges = <0x00000000 0x00000000 0xc0000000 0x00010000>,
        <0x00000001 0x00000038 0xff200038 0x00000008>,
        <0x00000001 0x00000020 0xff200020 0x00000010>,
        <0x00000001 0x00000010 0xff200010 0x00000010>,
        <0x00000001 0x00000000 0xff200000 0x00000010>,
        <0x00000001 0x00000030 0xff200030 0x00000008>;

    bitcrusher_0: bitcrusher@0x100000020 {
        compatible = "fe,bitcrusher-1.0", "dev,fe-bitcrusher";
        reg = <0x00000001 0x00000020 0x00000010>;
    }; //end bitcrusher@0x100000020 (bitcrusher_0)

    flanger_0: flanger@0x100000010 {
        compatible = "fe,flanger-1.0", "dev,fe-flanger";
        reg = <0x00000001 0x00000010 0x00000010>;
    }; //end flanger@0x100000010 (flanger_0)

    echo_0: echo@0x100000000 {
        compatible = "fe,echo-1.0", "dev,fe-echo";
        reg = <0x00000001 0x00000000 0x00000010>;
    }; //end echo@0x100000000 (echo_0)

    jtag_uart: serial@0x100000038 {
        compatible = "altr,juart-18.0", "altr,juart-1.0";
        reg = <0x00000001 0x00000038 0x00000008>;
        interrupt-parent = <0x2>;
        interrupts = <0 40 4>;
    }; //end serial@0x100000038 (jtag_uart)


    SystemID: sysid@0x100000030 {
        compatible = "altr,sysid-18.0", "altr,sysid-1.0";
        reg = <0x00000001 0x00000030 0x00000008>;
        id = <2899645186>;	/* embeddedsw.dts.params.id type NUMBER */
        timestamp = <1570477205>;	/* embeddedsw.dts.params.timestamp type NUMBER */
    }; //end sysid@0x100000030 (SystemID)
};
```

# Driver manager
`drivermgr.sh` loads and removes loadable kernel modules via `insmod` and `rmmod`. Nothing too special here. The main thing to note---which is a potential shortcoming---is that the script assumes that the kernel modules exist in a specific place. For example, the modules for the sound effects project must be at `/lib/modules/sound_effects`. 

## Usage
```
usage: drivermgr [-h] [-v] <command> directory

Load and remove kernel modules.

commands:
  load            load kernel module(s)
  remove          remove kernel module(s)

positional arguments:
  directory       directory name in /lib/modules/ that contains the modules to be loaded

optional arguments:
  -h, --help      display this help text
  -v, --verbose   print more details about what's going on
```

# Outstanding questions
- Where do we put these files? Should they live in a subdirectory in this repo, e.g. AWS? 
- Do we care about having a coding style for Bash scripts?

### CODE REVIEW

**Comment by fe-wickham** [comment]
So a potential solution to fixing the coupling of the use /lib/modules between scripts is to use environment variables such that the aws downloader script sets a system level environment variable to whatever is used as the driver path, even the default and then the driver manager script uses the environment variable if it is defined, otherwise it uses the default. Any updates to the aws downloader script driver path would then not require an update to the drivermgr as the environment variable will be updated at runtime.

**Comment by tvannoy** [comment]
> 
> 
> So a potential solution to fixing the coupling of the use /lib/modules between scripts is to use environment variables such that the aws downloader script sets a system level environment variable to whatever is used as the driver path, even the default and then the driver manager script uses the environment variable if it is defined, otherwise it uses the default. Any updates to the aws downloader script driver path would then not require an update to the drivermgr as the environment variable will be updated at runtime.

I like that idea. I'll give that some thought. Using environment variables could decrease some of the dependence on specific naming conventions as well.

**Comment by fe-tdavis** [comment]
I like adding environmental variables as well.  As long as the scripts aren't tied to a specific project, we should keep them in a subdirectory in this repo.  I think we should also have a coding style for bash scripts as well.  If there isn't a good reference style out there, we can create our own.  Either way, we should be consistent in all of our code.

**Comment by tvannoy** [comment]
I'll move forward with the environment variable idea. It makes the inevitable coupling more flexible. 

Any ideas for a directory name? The first thing that comes to mind is "aws", but only one of the scripts is actually related to AWS, so I'm not a big fan of that. 

I'll see if there's a good style guide out there. If not, we'll just modify what I currently have.

**Comment by fe-tdavis** [comment]
Sounds good.  That's a tough one...  Each of the scripts does something different, so that makes it a little more difficult to name them.  How about something general like fpga_reconfiguration since the FPGA will be reprogrammed after it has booted with the default .rbf on the device?

**Comment by rksnider** [comment]
How about "ost" for open speech tools?

Ross

**Comment by tvannoy** [comment]
I like fpga_reconfiguration, or fpga_runtime_config, or something similar. I think it's likely that we will eventually want to put some tools here for initial FPGA configuration, i.e. configuring before boot, so I'll be sure to emphasize the runtime/reconfiguration part to make the distinction.

**Comment by tvannoy** [comment]
If you all think this PR is good to go, I'll go ahead and merge it into the dev branch. Moving forward, I think it will be best to only merge to master for releases. It might be good to have somebody else test these scripts real quick before merging. 

### Script coupling
I opted not to go down the environment variable route because setting an environment variable within a script only exports that variable for the current process, not the parent process. Therefore, there's no clean way to directly export environmental variables because the variables will disappear after the script is done executing. 

Instead, I added a `--driver-path` argument to drivermgr. Users will have to provide the same --driver-path argument to both awsdownload.py and drivermgr (or just use the default 😃).

Additionally, I removed the `--firmware-path` option from awsdownload.py because the rbf needs to be on the firmware search path. You can apparently add a custom path to the firmware search path by writing to `/sys/module/firmware_class/parameters/path`, but that didn't seem to work. 

### Bug fixes and improvements
See the commit messages for details

### Bash style guide
I updated the scripts to follow [Google's shell style guide](https://google.github.io/styleguide/shellguide.html). They don't specify much, as shell shouldn't really be used for many programs. The only departure I made is to follow the numpy documentation style in function headers to match our python scripts.

**Pull request merged**
