### PR TITLE
Github actions

### PR DESCRIPTION
**Pull request by tvannoy**

### CODE REVIEW

**Review by fe-wickham — COMMENTED** [review]
This looks good to me, but before we merge it I'd like to see linting issues fixed as well as updating "buildrootfs.sh" so it is scanned by the linter. The reason for fixing issues before merge, is if we don't we are just expecting the linter to fail when we make updates, kind of missing the point of it.

**Comment by tvannoy** [comment]
> This looks good to me, but before we merge it I'd like to see linting issues fixed as well as updating "buildrootfs.sh" so it is scanned by the linter. The reason for fixing issues before merge, is if we don't we are just expecting the linter to fail when we make updates, kind of missing the point of it.

I agree. This should have been marked as a draft since it's just an experiment in progress to figure out how we can set up linting for our PRs in general.

**Comment by fe-wickham** [comment]
Do you know if we can select only certain paths for it to lint? I don't think its an issue for utils but if we want to start linting `simulink_codegen` it will take a bit more effort to get that fully compliant. Given that, it would be nice if we could just start linting certain folders

**Comment by fe-wickham** [comment]
> we can set up linting for our PRs in general.

This seems like a great way to do it, automatic and public.

**Comment by tvannoy** [comment]
> Do you know if we can select only certain paths for it to lint?

In general, that seems to be possible. It looks like it's dependent on whether the github actions we use support it. Both linters used here seem to support linting specific paths. For what it's worth, there are a lot of linter actions available on github, so there might be better ones than I chose here.

**Pull request closed without merging**
